import os
import datetime

SKILLS_DIR = '/Users/daniel/.gemini/antigravity/skills/'
WIKI_RAW_DIR = '/Users/daniel/dev/antigravity-dev/llm-wiki-dev/wiki/raw/'

def analyze_gstack():
    print(f"[Pipeline] Scanning gstack ecosystem at {SKILLS_DIR}...")
    
    if not os.path.exists(SKILLS_DIR):
        print(f"[Error] Skills directory not found.")
        return

    skills = []
    for skill_folder in os.listdir(SKILLS_DIR):
        skill_path = os.path.join(SKILLS_DIR, skill_folder)
        if os.path.isdir(skill_path):
            skill_md_path = os.path.join(skill_path, 'SKILL.md')
            intelligence_score = 0
            description = "No description available."
            
            if os.path.exists(skill_md_path):
                with open(skill_md_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                    intelligence_score = len(content) // 100 # Rough "intelligence density" metric
                    # Extract title/description roughly
                    lines = content.split('\n')
                    description = lines[0].replace('#', '').strip() if lines else "Skill module."

            skills.append({
                "name": skill_folder,
                "score": intelligence_score,
                "desc": description
            })

    # Sort by intelligence score
    skills.sort(key=lambda x: x['score'], reverse=True)

    # Build Analysis Vibe
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    vibe_content = f"""# Gstack Skill Ecosystem Analysis (Active Ingest)

> [!NOTE]
> This document was automatically generated by the 'Data-to-Knowledge Pipeline' on {timestamp}. 
> It analyzes the current localized gstack environment for strategic intelligence density.

## Executive Summary
Total of **{len(skills)} modules** detected in the active gstack skill path. 
Aggregate Intelligence Score: **{sum(s['score'] for s in skills)} pts**.

## Intelligence Density Ranking (Top 5)

| Rank | Skill Module | Intelligence Score | Description |
|:---|:---|:---|:---|
"""
    for i, skill in enumerate(skills[:5]):
        vibe_content += f"| {i+1} | `{skill['name']}` | **{skill['score']}** | {skill['desc']} |\n"

    vibe_content += """
## Technical Inference
High density modules (Score > 50) indicate **Strategic Core Competencies**. 
Low density modules (< 10) are optimized **Utility Scripts**. 

---
**Pipeline Status**: ✅ Data Ingested & Verified.
"""

    # Output to Wiki Raw Folder
    target_path = os.path.join(WIKI_RAW_DIR, 'gstack_analysis_vibe.md')
    with open(target_path, 'w', encoding='utf-8') as f:
        f.write(vibe_content)
    
    print(f"[Pipeline Success] Output: {target_path}")

if __name__ == "__main__":
    analyze_gstack()
